.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH POWERDEBUG 8 "September  3, 2010" "Linux" "PowerDebug Manual"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
powerdebug \- A tool to display regulator and sensor information 
.SH SYNOPSIS
.B powerdebug
.RB [[-r|-s|-c] [-v] [-d] [-t <ticktime>]]
.RB [-V]
.RB [-h]
.br
.SH DESCRIPTION
This tool can be used to display regulator, sensor and clock tree
related information.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBpowerdebug\fP is a tool that provides users extra information
about how the power is being managed in the system.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the Info files.
.TP
\fB\-r\fR, \fB\-\-regulator
  print regulator information.
.TP
\fB\-s\fR, \fB\-\-sensor
  print sensor information.
.TP
\fB\-c\fR, \fB\-\-clock
  print clock tree related information.
.TP
\fB\-t\fR, \fB\-\-time
  set the ticktime to specified value.
.TP
\fB\-v\fR, \fB\-\-verbose
  show detailed information.
.TP
\fB\-d\fR, \fB\-\-dump
  read and list information only once.
.TP
\fB\-V\fR, \fB\-\-version
  show version information and exit.
.TP
\fB\-h\fR, \fB\-\-help
  show usage details.
Show version of program.
.SH SEE ALSO
.BR powertop (8)
.br
.SH AUTHOR
powerdebug was written by Amit Arora <amit.arora@linaro.org>.
.PP
This manual page was written by Amit Arora <amit.arora@linaro.org>,
for the Debian project (and may be used by others).
